# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CSEG
email: cseg-officers@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  CSEG is the Computer Science and Engineering Graduate student organization of
  the Computer Science and Engineering department at the University of Michigan
  at Ann Arbor.  CSEG represents graduate students as representatives on a
  number of departmental committees. CSEG organizes social activities like
  cookouts, happy hours, and intramural sports. All CSE graduate students are
  automatically members of CSEG.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://um-cseg.github.io" # the base hostname & protocol for your site
github_username: um-cseg
twitter_username:
facebook_username:

# Build settings
markdown: kramdown
theme: minima

owner: CSEG
address:
  - line: Bob and Betty Beyster Building
  - line: 2260 Hayward St
  - line: Ann Arbor, MI 48109
telephone:
copyright:

# API settings
google_api_key:
